someValue: 4711

example:
    the-greeting: "Hello, World!"
    interval: 1000
    precision: 42.23
    servers:
        - name: "springbootbuch"
          url: "http://springbootbuch.de"

---
spring:
    profiles: "demo1"

example:
    the-greeting: "Hello, Demo1!"
    servers:
        - name: "demo"
          url: "http://test.com"

---
spring:
    profiles: "demo2"

example:
    the-greeting: "Hello, Demo2!"
    interval: 2000
    servers:
        - name: "bootifultodos"
          url: "http://bootifultodos.de"
